<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260608145511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создана таблица users + готовый test user (auth-service) + UUID';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $usersTable = "\"{$schemaName}\".\"users\"";

        /**
         * =========================
         * ENABLE UUID EXTENSION
         * =========================
         */
        $this->addSql('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');

        /**
         * =========================
         * CREATE TABLE
         * =========================
         */
        $this->addSql("
            CREATE TABLE {$usersTable}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                user_uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                email VARCHAR(255) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                patronymic VARCHAR(100),

                phone_number VARCHAR(20) NOT NULL,

                verification_channel_id CHARACTER VARYING(64)
                    COLLATE pg_catalog.\"default\" NOT NULL,

                password_hash VARCHAR(255) NOT NULL,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT users_pkey PRIMARY KEY (id),
                CONSTRAINT uq_users_uuid UNIQUE (user_uuid),
                CONSTRAINT uq_users_email UNIQUE (email),
                CONSTRAINT uq_users_phone_number UNIQUE (phone_number)
            )
        ");

        /**
         * =========================
         * COMMENTS
         * =========================
         */
        $this->addSql("
            COMMENT ON COLUMN {$usersTable}.id IS 'Surrogate primary key'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$usersTable}.user_uuid IS 'Public unique user identifier (UUID)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$usersTable}.email IS 'User email used for authentication'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$usersTable}.verification_channel_id IS 'External verification channel identifier (no FK due to microservices architecture)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$usersTable}.password_hash IS 'BCrypt hashed password'
        ");

        /**
         * =========================
         * INDEXES
         * =========================
         */
        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_users_email
            ON {$usersTable} (email)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_users_phone_number
            ON {$usersTable} (phone_number)
        ");

        /**
         * =========================
         * SEED TEST USER
         * =========================
         */
        $this->addSql("
            INSERT INTO {$usersTable} (
                user_uuid,
                email,
                last_name,
                first_name,
                patronymic,
                phone_number,
                verification_channel_id,
                password_hash,
                created_at,
                updated_at
            )
            VALUES (
                gen_random_uuid(),
                'test@example.com',
                'Ivanov',
                'Ivan',
                'Ivanovich',
                '+79991234567',
                'email',
                :password_hash,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            )
        ", [
            'password_hash' => '$2y$12$8lXZ3zcf8KED7C0bIRDbGuLOgBWto4EHAjIHv.PoE9fLMM0/XllOm'
        ]);
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $usersTable = "\"{$schemaName}\".\"users\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$usersTable}
        ");
    }
}
