<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260703120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Таблица связи пользователя auth-service с company_id из verification-service';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"users_companies_link\"";

        $this->addSql("
            CREATE TABLE {$table}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                user_uuid UUID NOT NULL,
                company_id BIGINT NOT NULL,

                source_service VARCHAR(64) NOT NULL DEFAULT 'verification-service',

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT users_companies_link_pkey PRIMARY KEY (id),
                CONSTRAINT uq_users_companies_link_user_uuid UNIQUE (user_uuid),
                CONSTRAINT uq_users_companies_link_company_id UNIQUE (company_id)
            )
        ");

        $this->addSql("
            COMMENT ON TABLE {$table}
            IS 'Связь пользователя auth-service с компанией, данные которой хранятся в verification-service'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.user_uuid
            IS 'Public user UUID from auth.users.user_uuid'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.company_id
            IS 'Company ID from verification.companies'
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_users_companies_link_user_uuid
            ON {$table} (user_uuid)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_users_companies_link_company_id
            ON {$table} (company_id)
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"users_companies_link\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$table}
        ");
    }
}
