<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260615141000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Таблица refresh_tokens (1 active refresh token per user)';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"refresh_tokens\"";

        $this->addSql("
            CREATE TABLE {$table}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                user_id BIGINT NOT NULL,

                refresh_token_hash VARCHAR(255) NOT NULL,

                expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                revoked_at TIMESTAMP WITHOUT TIME ZONE,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),

                CONSTRAINT uq_refresh_tokens_user_id UNIQUE (user_id)
            )
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.user_id
            IS 'User ID from users table (no FK due to microservices architecture)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.refresh_token_hash
            IS 'SHA-256 or bcrypt hash of refresh token'
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id
            ON {$table} (user_id)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
            ON {$table} (expires_at)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_refresh_tokens_revoked_at
            ON {$table} (revoked_at)
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"refresh_tokens\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$table}
        ");
    }
}
